Actions.openBox.layout={
	title = [=[开金币宝箱]=],
	x = 0,
	y = 0,
	width = 100,
	height = 100,
	
	tags = {
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'goldBox',
			value = [=[金宝箱]=],
			action = 'openGoldBox',
			x = 30,
			y = 60,
			width = 80,
			height = 45,
		},
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'goldBoxState',
			value = [=[ 每次开启需5金/点击左侧即开启]=],
			action = '',
			x = 130,
			y = 60,
			width = 80,
			height = 70,
		},
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'silverBox',
			value = [=[银宝箱]=],
			action = 'openSilverBox',
			x = 30,
			y = 115,
			width = 80,
			height = 45,
		},
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'silverBoxState',
			value = [=[ 每次开启需3金/点击左侧即开启]=],
			action = '',
			x = 130,
			y = 115,
			width = 80,
			height = 70,
		},
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'copperBox',
			value = [=[铜宝箱]=],
			action = 'openCopperBox',
			x = 30,
			y = 170,
			width = 80,
			height = 45,
		},
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'copperBoxState',
			value = [=[每次开启需50银点击左侧即开启]=],
			action = '',
			x = 130,
			y = 170,
			width = 80,
			height = 70,
		},
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'goldBoxRules',
			value = [=[游戏规则]=],
			action = 'goldBoxRules',
			x = 30,
			y = 225,
			width = 80,
			height = 45,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.left,
			name = 'fastRefreshGoldBox',
			value = [=[快速刷新]=],
			action = 'fastRefreshGoldBox',
			x = 7,
			y = 295,
			width = 60,
			height = 18,
		},
		{
			type = TagType.input,
			subtype = TagSubType.right,
			name = 'gameList',
			value = [=[返回]=],
			action = 'gameList',
			x = 173,
			y = 295,
			width = 60,
			height = 18,
		},
	},
}