Actions.accept.layout={
	title = [=[老虎棒子鸡]=],
	x = 0,
	y = 0,
	width = 100,
	height = 100,
	
	tags = {
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'acceptTiger',
			value = [=[老虎]=],
			action = 'acceptTiger',
			x = 12,
			y = 76,
			width = 55,
			height = 24,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'acceptStick',
			value = [=[棒子]=],
			action = 'acceptStick',
			x = 92,
			y = 76,
			width = 55,
			height = 24,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'acceptChicken',
			value = [=[鸡]=],
			action = 'acceptChicken',
			x = 174,
			y = 76,
			width = 55,
			height = 24,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'inningName',
			value = '',
			display = '',
			action = '',
			x = 12,
			y = 110,
			width = 203,
			height = 43,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.inputLable,
			name = 'inning',
			value = [=[0]=],
			display = [=[0]=],
			action = '',
			x = 80,
			y = 110,
			width = 50,
			height = 12,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'playerGold',
			value = '',
			action = '',
			x = 12,
			y = 141,
			width = 120,
			height = 12,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'remark',
			value = [=[备注：如果对方获胜您投入的游戏币将全部输光，如果您获胜，您将获得投入游戏币的90%的奖励，如果平局退回游戏币。]=],
			action = '',
			x = 12,
			y = 189,
			width = 203,
			height = 43,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.left,
			name = 'cyclesRules',
			value = [=[游戏规则]=],
			action = 'cyclesRules',
			x = 7,
			y = 295,
			width = 60,
			height = 18,
		},
		
		
		{
			type = TagType.input,
			subtype = TagSubType.right,
			name = 'cycles',
			value = [=[返回]=],
			action = 'cycles',
			x = 173,
			y = 295,
			width = 60,
			height = 18,
		},
	},
}