Actions.betAccount.layout={
	title = [=[元宝赌数]=],
	x = 0,
	y = 0,
	width = 100,
	height = 100,
	
	tags = {
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'money',
			value = [=[请输入下注金额/  最少20元宝]=],
			action = '',
			x = 20,
			y = 45,
			width = 100,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.number,
			name = 'yuanbaoForBet',
			value = [=[0]=],
			action = '',
			x = 150,
			y = 47,
			width = 54,
			height = 23,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'lastResult',
			value = '',
			action = '',
			x = 24,
			y = 255,
			width = 120,
			height = 12,
		},	
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'getResultLeftTime',
			value = '',
			action = '',
			x = 24,
			y = 275,
			width = 120,
			height = 12,
		},	
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'betAccountRefresh',
			value = [=[刷新]=],
			action = 'betAccount',
			x = 100,
			y = 295,
			width = 36,
			height = 18,
		},
		{
			type = TagType.input,
			subtype = TagSubType.left,
			name = 'betAccountRules',
			value = [=[游戏规则]=],
			action = 'betAccountRules',
			x = 7,
			y = 295,
			width = 60,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.right,
			name = 'gameList',
			value = [=[返回]=],
			action = 'gameList',
			x = 173,
			y = 295,
			width = 60,
			height = 18,
		},
	},
}