Actions.guess.layout={
	title = [=[猜猜看]=],
	x = 0,
	y = 0,
	width = 100,
	height = 100,
	
	tags = {
		{
			type = TagType.input,
			subtype = TagSubType.number,
			name = 'goldForGuess',
			value = [=[0]=],
			action = '',
			x = 26,
			y = 66,
			width = 100,
			height = 18,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'silver',
			value = [=[银]=],
			action = '',
			x = 150,
			y = 66,
			width = 12,
			height = 12,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'big',
			value = [=[大]=],
			action = 'big',
			x = 28,
			y = 110,
			width = 18,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'small',
			value = [=[小]=],
			action = 'small',
			x = 64,
			y = 110,
			width = 18,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'single',
			value = [=[单]=],
			action = 'single',
			x = 99,
			y = 110,
			width = 18,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'double',
			value = [=[双]=],
			action = 'double',
			x = 134,
			y = 110,
			width = 18,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'sweep',
			value = [=[豹子]=],
			action = 'sweep',
			x = 170,
			y = 110,
			width = 36,
			height = 18,
		},
		
		
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'ratio1',
			value = [=[1赔2]=],
			action = '',
			x = 25,
			y = 135,
			width = 20,
			height = 12,
		},
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'ratio2',
			value = [=[1赔2]=],
			action = '',
			x = 60,
			y = 135,
			width = 20,
			height = 12,
		},
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'ratio3',
			value = [=[1赔2]=],
			action = '',
			x = 95,
			y = 135,
			width = 20,
			height = 12,
		},
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'ratio4',
			value = [=[1赔2]=],
			action = '',
			x = 130,
			y = 135,
			width = 20,
			height = 12,
		},
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'ratio5',
			value = [=[1赔18]=],
			action = '',
			x = 172,
			y = 135,
			width = 30,
			height = 12,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'playerGold',
			value = '',
			action = '',
			x = 26,
			y = 175,
			width = 120,
			height = 12,
		},

		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'lastResult',
			value = '',
			action = '',
			x = 26,
			y = 210,
			width = 200,
			height = 12,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'openResultLeftTime',
			value = '',
			action = '',
			x = 26,
			y = 245,
			width = 120,
			height = 12,
		},	
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'guessRefresh',
			value = [=[刷新]=],
			action = 'guess',
			x = 162,
			y = 242,
			width = 36,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.left,
			name = 'guessRules',
			value = [=[游戏规则]=],
			action = 'guessRules',
			x = 7,
			y = 295,
			width = 60,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.right,
			name = 'gameList',
			value = [=[返回]=],
			action = 'gameList',
			x = 173,
			y = 295,
			width = 60,
			height = 18,
		},
	},
}