Actions.bigOrSmall.layout={
	title = [=[押大小]=],
	x = 0,
	y = 0,
	width = 100,
	height = 100,
	
	tags = {
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'big',
			value = [=[大]=],
			action = '',
			x = 45,
			y = 57,
			width = 12,
			height = 12,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'rate',
			value = [=[赔率 1 : 2]=],
			action = '',
			x = 162,
			y = 132,
			width = 108,
			height = 12,
		},

		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'small',
			value = [=[小]=],
			action = '',
			x = 183,
			y = 57,
			width = 12,
			height = 12,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.number,
			name = 'goldForBig',
			value = [=[0]=],
			action = '',
			x = 26,
			y = 80,
			width = 48,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.number,
			name = 'goldForSmall',
			value = [=[0]=],
			action = '',
			x = 162,
			y = 80,
			width = 48,
			height = 18,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'unitForBig',
			value = [=[银]=],
			action = '',
			x = 44,
			y = 105,
			width = 12,
			height = 12,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'unitForSmall',
			value = [=[银]=],
			action = '',
			x = 183,
			y = 105,
			width = 12,
			height = 12,
		},		
				
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'bet',
			value = [=[押注]=],
			action = 'betBigOrSmall',
			x = 102,
			y = 128,
			width = 36,
			height = 18,
		},

		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'playerGold',
			value = '',
			action = '',
			x = 24,
			y = 181,
			width = 120,
			height = 12,
		},

		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'lastResult',
			value = '',
			action = '',
			x = 24,
			y = 213,
			width = 120,
			height = 12,
		},
		
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'openResultLeftTime',
			value = '',
			action = '',
			x = 24,
			y = 246,
			width = 120,
			height = 12,
		},	
		
		{
			type = TagType.input,
			subtype = TagSubType.submit,
			name = 'bigOrSmallRefresh',
			value = [=[刷新]=],
			action = 'bigOrSmall',
			x = 162,
			y = 246,
			width = 36,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.left,
			name = 'bigOrSmallRules',
			value = [=[游戏规则]=],
			action = 'bigOrSmallRules',
			x = 7,
			y = 295,
			width = 60,
			height = 18,
		},
		
		{
			type = TagType.input,
			subtype = TagSubType.right,
			name = 'gameList',
			value = [=[返回]=],
			action = 'gameList',
			x = 173,
			y = 295,
			width = 60,
			height = 18,
		},
	},
}