Actions.jinyaoshi.layout={
	title = [=[每日开奖]=],
	x = 0,
	y = 0,
	width = 100,
	height = 100,
	
	tags = {
		{
			type = TagType.label,
			subtype = TagSubType.none,
			name = 'money',
			value = [=[您的金钥匙不足///请输入购买///的金钥匙数]=],
			action = 'shangCheng',
			x = 20,
			y = 45,
			width = 120,
			height = 30,
		},{
			type = TagType.input,
			subtype = TagSubType.number,
			name = 'jinyaoshinumber',
			value = [=[0]=],
			action = '',
			x = 150,
			y = 67,
			width = 54,
			height = 23,
		},{
			type = TagType.input,
			subtype = TagSubType.left,
			name = 'goldBox1',
			value = [=[确定]=],
			action = 'buyjinyaoshi',
			x = 7,
			y = 295,
			width = 60,
			height = 18,
		},
		{
			type = TagType.input,
			subtype = TagSubType.right,
			name = 'gameList',
			value = [=[返回]=],
			action = 'gameList',
			x = 173,
			y = 295,
			width = 60,
			height = 18,
		},
	},
}