yuanBaoOpConst = {
	Buy_ITEM_FROM_MALL = 1,
	OPEN_YUANBAO_GOLD_BOX = 2,
	OPEN_YUANBAO_SILVER_BOX = 3,
	OPEN_YUANBAO_COPPER_BOX = 4,
	FASTREFRESH_GOLD_BOX = 5,
	FASTREFRESH_YUANBAO_BOX = 6,
	BET_ACCOUNT = 7,
	BUY_JINYAOSHI = 9,
	BUY_BOSS=10,
}